# Numpy: Arrays - Indexing, Selection & Operations 

In [2]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(3,5)

array([[0.30102989, 0.0039919 , 0.6672753 , 0.43163114, 0.37712881],
       [0.58622356, 0.16300514, 0.11037562, 0.8129983 , 0.46080849],
       [0.3483691 , 0.54940466, 0.86295904, 0.75565831, 0.92678175]])

In [13]:
arr = np.arange(0,11)

In [14]:
arr [0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr [:6]

array([0, 1, 2, 3, 4, 5])

In [16]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[10]

10

In [18]:
sliced_array = arr [0:5]

In [19]:
sliced_array

array([0, 1, 2, 3, 4])

In [24]:
td_array = np.array([[3, 5, 7], [4, 5, 8], [3, 6, 9]])

In [25]:
td_array

array([[3, 5, 7],
       [4, 5, 8],
       [3, 6, 9]])

In [30]:
td_array[1:,1:]

array([[5, 8],
       [6, 9]])

In [ ]:
arr_td